bcc/users/urls.py
from django.urls import path

from bcc.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # todo temp as template until we decide where in wagtail it goes
    path(
        "leaflet/",
        TemplateView.as_view(template_name="pages/leaflet.html"),
        name="leaflet",
    ),
    path(
        "story/",
        TemplateView.as_view(template_name="stories/story.html"),
        name="story",
    ),
    path(
        "d3/",
        TemplateView.as_view(template_name="pages/d3.html"),
        name="d3",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("bcc.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("digger/", include("activecollab_digger.urls")),
    path("cms/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("pages/", include(wagtail_urls)),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

bcc/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for bcc."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

bcc/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

bcc/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

bcc/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

bcc/templates/base.html
{% load static i18n compress %}<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}bcc{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Brightening the Covenant Chain">
  <meta name="author" content="King's Digital Lab">

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
  <![endif]-->

  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

  {% block css %}

    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <!-- Your stuff: Third-party CSS libraries go here -->
    {% compress css %}
      <!-- This file stores project-specific CSS -->

      <link href="{% static 'css/project.css' %}" rel="stylesheet">

    {% endcompress %}
    {% block extra_css %}
    {% endblock %}
  {% endblock %}
  <!-- Le javascript
  ================================================== -->
  {# Placed at the top of the document so pages load faster with defer #}
  {% block javascript %}

    <!-- Bootstrap JS and its dependencies-->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT"
            crossorigin="anonymous"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script defer src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>

    <!-- Your stuff: Third-party javascript libraries go here -->


    <!-- place project specific Javascript in this file -->
    {% compress js %}
      <script defer src="{% static 'js/project.js' %}"></script>
    {% endcompress %}

  {% endblock javascript %}
  {% block extra_js %}
  {% endblock %}

</head>

<body>

<div class="mb-1">
  <nav class="navbar navbar-expand-md navbar-light bg-light">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'home' %}">bcc</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">About</a>
        </li>
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a class="nav-link" href="{% url 'users:detail' request.user.username %}">{% trans "My Profile" %}</a>
          </li>
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
          </li>
        {% else %}
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
          </li>
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>

</div>

<div class="container">

  {% if messages %}
    {% for message in messages %}
      <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span></button>
      </div>
    {% endfor %}
  {% endif %}

  {% block content %}
    <p>Use this document as a way to quick start any new project.</p>
  {% endblock content %}

</div> <!-- /container -->

<div class="footer">
  <a href="https://www.kdl.kcl.ac.uk/cookie-use/">Cookies</a>
  <a href="https://www.kdl.kcl.ac.uk/privacy-policy/">Privacy Policy</a>
</div>

{% block modal %}{% endblock modal %}

{% block inline_javascript %}
  {# Script tags with only code, no src (defer by default) #}
{% endblock inline_javascript %}
</body>
</html>

bcc/templates/pages/about.html
{% extends "base.html" %}

bcc/templates/pages/d3.html
{% extends "base.html" %}

{% block extra_css %}
  <style>
    svg {
      border: 1px solid #eee;
    }

    .map path {
      fill: #ffffff;
      stroke: #777777;

    }


  </style>
{% endblock %}

{% block extra_js %}
  <script src="https://d3js.org/d3.v7.min.js"></script>


{% endblock %}


{% block content %}
  <div id="basemapBlock" style="display: grid; grid-template-columns: 75% 25%">
    <div id="mapContainer" style="height: 800px;width: 800px">
      <svg width="800" height="800">
        <g class="map"></g>
        <g class="bounding-box">
          <rect></rect>
        </g>
        <g class="centroid">
          <circle r="4"></circle>
        </g>
      </svg>
    </div>
    <div id="sidebar">
      <h1>Story</h1>
      <h2 class="title">Text could go here</h2>
    </div>
  </div>

  <script>
    let geojson;
    let features = {
      "type": "FeatureCollection",
      "name": "BCC_points_export_07march22",
      "crs": {"type": "name", "properties": {"name": "urn:ogc:def:crs:OGC:1.3:CRS84"}},
      "features": [
        {
          "type": "Feature",
          "properties": {
            "id": null,
            "feat_type": 1,
            "sub_type": 1,
            "map_source": 1,
            "date_yr": 1975,
            "map_text": "Noo York",
            "norm_text": "New York",
            "accuracy": 1
          },
          "geometry": {"type": "Point", "coordinates": [-73.806975078231048, 40.901800182986982]}
        },
        {
          "type": "Feature",
          "properties": {
            "id": null,
            "feat_type": 5,
            "sub_type": 4,
            "map_source": 12,
            "date_yr": 1755,
            "map_text": "French House",
            "norm_text": "French House",
            "accuracy": 2
          },
          "geometry": {"type": "Point", "coordinates": [-66.048401017803627, 49.51321377352896]}
        },
        {
          "type": "Feature",
          "properties": {
            "id": null,
            "feat_type": 5,
            "sub_type": 4,
            "map_source": 12,
            "date_yr": 1755,
            "map_text": "English H.",
            "norm_text": "English House",
            "accuracy": 2
          },
          "geometry": {"type": "Point", "coordinates": [-66.329719711006589, 49.286173106646224]}
        },
        {
          "type": "Feature",
          "properties": {
            "id": null,
            "feat_type": 1,
            "sub_type": 2,
            "map_source": 12,
            "date_yr": 1755,
            "map_text": "Ye Olde Neil's Place",
            "norm_text": "Neil's Place",
            "accuracy": 2
          },
          "geometry": {"type": "Point", "coordinates": [-66.955994100403643, 48.844965097545895]}
        },
        {
          "type": "Feature",
          "properties": {
            "id": null,
            "feat_type": 1,
            "sub_type": 1,
            "map_source": 1,
            "date_yr": 1590,
            "map_text": "Roanoac",
            "norm_text": "Roanoke",
            "accuracy": 1
          },
          "geometry": {"type": "Point", "coordinates": [-75.861013916563678, 35.850792882051685]}
        },
        {
          "type": "Feature",
          "properties": {
            "id": null,
            "feat_type": 3,
            "sub_type": 2,
            "map_source": 8,
            "date_yr": 1752,
            "map_text": "CAPE MAY CO.",
            "norm_text": "Cape May Company",
            "accuracy": 4
          },
          "geometry": {"type": "Point", "coordinates": [-74.794524114181897, 39.225419600607907]}
        },
        {
          "type": "Feature",
          "properties": {
            "id": null,
            "feat_type": 1,
            "sub_type": 2,
            "map_source": 8,
            "date_yr": 1752,
            "map_text": "Leeds",
            "norm_text": "Leeds",
            "accuracy": 3
          },
          "geometry": {"type": "Point", "coordinates": [-74.444349048008235, 39.489407284905724]}
        },
        {
          "type": "Feature",
          "properties": {
            "id": null,
            "feat_type": 1,
            "sub_type": 2,
            "map_source": 8,
            "date_yr": 1752,
            "map_text": "Greenwich",
            "norm_text": "Greenwich",
            "accuracy": 3
          },
          "geometry": {"type": "Point", "coordinates": [-75.309781711551707, 39.394757262425429]}
        },
        {
          "type": "Feature",
          "properties": {
            "id": null,
            "feat_type": 1,
            "sub_type": 2,
            "map_source": 8,
            "date_yr": 1752,
            "map_text": "Salem",
            "norm_text": "Salem",
            "accuracy": 3
          },
          "geometry": {"type": "Point", "coordinates": [-75.466109866093518, 39.571397497760223]}
        },
        {
          "type": "Feature",
          "properties": {
            "id": null,
            "feat_type": 1,
            "sub_type": 2,
            "map_source": 8,
            "date_yr": 1752,
            "map_text": "Dover",
            "norm_text": "Dover",
            "accuracy": 3
          },
          "geometry": {"type": "Point", "coordinates": [-75.604929267326625, 39.093537216162069]}
        },
        {
          "type": "Feature",
          "properties": {
            "id": null,
            "feat_type": 1,
            "sub_type": 2,
            "map_source": 8,
            "date_yr": 1752,
            "map_text": "Salisbury",
            "norm_text": "Salisbury",
            "accuracy": 3
          },
          "geometry": {"type": "Point", "coordinates": [-75.651202401071004, 39.254478013267423]}
        },
        {
          "type": "Feature",
          "properties": {
            "id": null,
            "feat_type": 1,
            "sub_type": 2,
            "map_source": 8,
            "date_yr": 1752,
            "map_text": "New T.",
            "norm_text": "New Town",
            "accuracy": 3
          },
          "geometry": {"type": "Point", "coordinates": [-76.085169358079071, 39.204102448677183]}
        },
        {
          "type": "Feature",
          "properties": {
            "id": null,
            "feat_type": 1,
            "sub_type": 2,
            "map_source": 8,
            "date_yr": 1752,
            "map_text": "George T",
            "norm_text": "Georgetown",
            "accuracy": 3
          },
          "geometry": {"type": "Point", "coordinates": [-76.062658103825058, 39.357054644423748]}
        },
        {
          "type": "Feature",
          "properties": {
            "id": null,
            "feat_type": 1,
            "sub_type": 2,
            "map_source": 8,
            "date_yr": 1752,
            "map_text": "Noxontown",
            "norm_text": "Noxontown",
            "accuracy": 3
          },
          "geometry": {"type": "Point", "coordinates": [-75.678716156270369, 39.369624446102456]}
        },
        {
          "type": "Feature",
          "properties": {
            "id": null,
            "feat_type": 1,
            "sub_type": 2,
            "map_source": 8,
            "date_yr": 1752,
            "map_text": "St. George",
            "norm_text": "St George",
            "accuracy": 3
          },
          "geometry": {"type": "Point", "coordinates": [-75.644949274889356, 39.500988243033909]}
        },
        {
          "type": "Feature",
          "properties": {
            "id": null,
            "feat_type": 1,
            "sub_type": 2,
            "map_source": 8,
            "date_yr": 1752,
            "map_text": "New Castle",
            "norm_text": "Newcastle",
            "accuracy": 3
          },
          "geometry": {"type": "Point", "coordinates": [-75.548651131691585, 39.66388174599917]}
        },

      ]
    };

    let projection = d3.geoMercator()
            .scale(800)
            .translate([400, 400])
            .center([-65.6572396, 49.5222944]);

    let geoGenerator = d3.geoPath().pointRadius(5).projection(projection);

    function handleMouseover(e, d) {
      if (d.properties && d.properties.norm_text) {

        let pixelArea = geoGenerator.area(d);
        let bounds = geoGenerator.bounds(d);
        let centroid = geoGenerator.centroid(d);
        let measure = geoGenerator.measure(d);

        d3.select('#sidebar .title')
                .text(d.properties.norm_text);

        d3.select('#mapContainer .bounding-box rect')
                .attr('x', bounds[0][0])
                .attr('y', bounds[0][1])
                .attr('width', bounds[1][0] - bounds[0][0])
                .attr('height', bounds[1][1] - bounds[0][1]);

        d3.select('#mapContainer .centroid')
                .style('display', 'inline')
                .attr('transform', 'translate(' + centroid + ')');
      }
    }

    function updateWorldMap() {
      // Update world map
      let allFeatures = geojson.features.concat(features.features)
      let u = d3.select('g.map')
              .selectAll('path')
              .data(allFeatures)
              .join('path')
              .attr('d', geoGenerator)
              .on('mouseover', handleMouseover)
              .style('fill', function (feature) {
                if (feature.properties && feature.properties.feat_type) {
                  switch (feature.properties.feat_type) {
                    case 1:
                      return 'orange';
                    case 3:
                      return 'red';
                    case 5:
                      return 'blue';
                    default:
                      return '#ffffff';
                  }
                }
                return '#ffffff';

              });


    }

    d3.json('https://gist.githubusercontent.com/d3indepth/f28e1c3a99ea6d84986f35ac8646fac7/raw/c58cede8dab4673c91a3db702d50f7447b373d98/ne_110m_land.json')
            .then(function (json) {
              geojson = json;
              updateWorldMap();
            });

  </script>
{% endblock %}

bcc/templates/pages/home.html
{% extends "base.html" %}

bcc/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

bcc/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}